# Generated by Django 4.2.2 on 2023-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0004_alter_shortener_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='url_index',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
