# Generated by Django 4.2.2 on 2023-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0005_shortener_url_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='url_alias',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
