# Generated by Django 4.2.2 on 2023-06-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0006_shortener_url_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='url_alias',
        ),
    ]
