# Generated by Django 4.2.2 on 2023-06-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0008_alter_shortener_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.URLField(max_length=500),
        ),
    ]
