# Generated by Django 4.2.2 on 2023-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0009_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='url_alias',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
